const replies = [
    "ano",
    "why",
    "sino",
    "sml mo lang",
    "sml mo ngane",
    "di nga?",
    "cholesterol mo bab",
    "highblood mode to whahaha",
    "tangina naman",
    "HAHAHAHA",
    "hala",
    "hala sige",
    "sus",
    "ok lang",
    "go lang",
    "ayaw ko na",
    "edi wow",
    "eme lang",
    "charot lang",
    "sana ol",
    "bet",
    "no way",
    "yikes",
    "nako",
    "char",
    "lol",
    "lmao",
    "haha",
    "teh",
    "chika mo nga",
    "diba nga",
    "ay oo nga pala",
    "aba talaga",
    "grabe ka",
    "edi sige",
    "ano ba yan",
    "nag-iinarte",
    "ganon ba",
    "huy",
    "teka lang",
    "sabagay",
    "meh",
    "ampota",
    "eto na",
    "ayan na",
    "wew",
    "wala ka talaga",
    "ay nako",
    "hay nako",
    "lods",
    "beh",
    "babe",
    "char ha",
    "ikr",
    "mood",
    "valid",
    "periodt",
    "slay",
    "lowkey",
    "highkey",
    "no cap",
    "bruh",
    "chile",
    "sheesh",
    "okurrr",
    "bestie",
    "sis",
    "anong meron",
    "anung nangyari",
    "chismis",
    "spill",
    "spill the tea",
    "tea pls",
    "kulit mo talaga",
    "baliw ka",
    "grabe",
    "kaloka",
    "ka-cute naman",
    "adik",
    "gago",
    "pakshet",
    "ulol",
    "leche",
    "putang ina",
    "kaya mo yan",
    "laban lang",
    "keri mo yan",
    "go beshie",
    "cheer up babskie",
    "ok ka lang?",
    "ingat",
    "mahal kita",
    "huy wag ganyan",
    "oy",
    "uy",
    "ay",
    "oops",
    "oooh",
    "ahhh",
    "hmm",
    "eh",
    "di ko alam",
    "baka",
    "siguro",
    "depende",
    "parang ganon",
    "akala mo bot noh?",
];

const imageReplies = [];

module.exports = { replies, imageReplies };
