// =============================================
// AUTO-REPLY TEXT MESSAGES
// Replace each "word#" with your own text.
// The bot picks one randomly each time.
// =============================================

const replies = [
    "Shuapemoko",
    "sml DogsStylish Ko mamamo",
    "ooAkobossmo",
    "Sml Mo lang Kalabaw",
    "Tohogen Ko powetmo",
    "Moka Ka tilapia",
    "Inis Nato?",
    "Wag ka Homagolgol",
    "Somisigawkaba",
    "Es M L mo Lang",
    "Ah Ala ka tatay",
    "Ops AlAka Tatay",
    "AYt Sobra Na Babski Yan Insan",
    "Shuepaen Moko MagDamag",
    "Anuepah Shushuebue Nato",
    "SigehShopapamore",
    "SiNoBOt",
    "WALAbotRetoh",
    "Owshesh",
    "MokaKaLoLO",
    "SmL Parruth",
    "SKLKoLANG Btway",
    "Ops Inisnato",
    "SmL Moka ka Piatos",
    "ncOneAzo",
    "Wowashuka",
    "anopa next",
    "tas tini/ra ko atemo e",
    "HIhI Moka Ka walis tAmbu",
    "Loko Ala ako Paki",
    "Eddiewow",
    "SanaoL Anak Ng tepaklong",
    "Owshet Walaka Ma/ma",
    "Ganyan Ka Ba Ka Ta/ba",
    "Osge Overweight Kâ",
    "Haysnakuh Tabaka",
    "Apaka Babskie?",
    "Yunoh SoledmoShomopa",
    "NaysoneShopanayan",
    "Yown Moka ka Ashu",
    "Wowmoka Ka Garapata",
    "Ikalma Mo cholesterol Mo Bab",
    "Hay Nako HighBluud Mode Na Yarn?",
    "Eddiewow Giraffe",
    "Es M l Moka Ka platito",
    "AsHu kAe ",
    "EeYaK Na tOnG aShUkO",
    "wAwW WaLaKa pAlAg sAkEn E!!",
    "bAlItAkO iKaWpInAkA pEgGiE DeTo!!",
    "shongke tayo magdamag",
    "oh na hhighblood ka na",
    "oh tumataas na bp mo",
    "oh cholesterol mo sa batok",
    "ahaha Bye Tolog Nako Lomapag Nayong Mokang Alimasag Ahaha Rilit Mona Isa Jan Baka Makick 😂",
    "Lods Iwan MonaLola Mong dinikit Kosa Pader Wag Molang ako iiwan Ahahah 😂",
    "Lods WagMo KaininDiaper Nang LoLaKo Bads Four You're Healhts* Ahahah TryLang Mag Englihs 😂",
    "Bayaw Hindi Ko Mababasa Yan Bolag ako  ahahaa 😂",
    "Bayaw LowaMo Bangkoan Namen 😂",
    "AlUkKo sToP It RiGhT nOw bAbSkIe tRy Ko lAnG MaG iNgLiSh Btw😆😁",
    "nAkEkEtA NiYo bA NaSaN nAg ChAChAt  AhUhUhU!!😁😆",
    "mOkA Ka JeLlFiSh BtW Way🤣🤪",
    "𝐴𝑘𝑜 𝑇𝑜 𝑆𝑖 𝐽𝑜𝑠𝑒 𝑅𝑖𝑧𝑎𝑙",
    "𝑆𝑚𝑙 𝑀𝑜𝑘𝑎 𝐾𝑎 𝑏𝐴𝑘𝑜𝑙𝑎𝑤",
    "𝑊𝑜𝑝𝑆𝑘𝑖𝑒 𝑊𝑎𝑔 𝐾𝑎 𝑚𝑎𝑔 𝐷𝑎𝑏𝑢𝑔",
    "𝑜𝑤𝑠ℎ𝑖𝑒 𝑀𝑜𝑘𝑎 𝑘𝑎 𝑃𝑜𝑤𝑖𝑡",
    "𝐸𝑠 𝑀 𝐿 𝐵𝑎𝑏𝑦 𝑅𝑜𝑐𝑘𝑒𝑡 Ka😅",
    "𝐴𝑛𝑜 𝑆𝑎𝑦𝑀𝑢 𝐴𝑛𝑡𝑎𝑣𝑎𝑀𝑢",
    "𝑊𝑎ℎ𝑎ℎ𝑎 𝐿𝑒𝑔𝑜 𝑁𝑎𝑚𝑎𝑛 Next😆😆",
     "🇸 🇲 🇱  🇲 🇴 🇰 🇦  🇰 🇦  🇹 🇴 🇹 🇴 🇧 🇪 ",
    " 🇦 🇳 🇸 🇦 🇧 🇪 🇭  🇲 🇺 🇭  🇹 🇦 🇻 🇦 🇰 🇦 🇼 🇦 🇭 🇦 🇭 🇦 ",
    "🇮 🇳 🇮 🇸 🇳 🇦 🇹 🇴 ",
    "🇼 🇦 🇱 🇦  🇧 🇴 🇹  🇷 🇮 🇹 🇴  🇧 🇹 🇼 🇦 🇾 ",
    "🇦 🇳 🇺 🇭  🇱 🇺 🇬 🇰 🇲 🇴 🇰  🇰 🇳 🇦  🇧 🇦 😆",
    "🇴 🇼 🇸 🇭 🇮 🇪  🇮 🇳 🇪 🇸 🇳 🇦 🇹 🇴 ",
    "🇼 🇦 🇭 🇦 🇭  🇧 🇦 🇬 🇦 🇱 🇦 🇳  🇲 🇴  🇵 🇦 ",
    "🇪 🇾 🇹  🇲 🇴 🇰 🇦  🇰 🇦  🇲 🇮 🇳 🇪 🇨 🇷 🇦 🇫 🇹 ",
    "🇴 🇼 🇸 🇭 🇮 🇪  🇺 🇱 🇦 🇲 🇰 🇴  🇦 🇩 🇴 🇧 🇴 ",
    "🇸 🇭 🇺 🇸 🇭 🇺 🇵 🇦 🇪  🇳 🇦  🇾 🇦 🇳 ",
    "🇾 🇴 🇭 🇴 🇴  🇲 🇴 🇰 🇴  🇰 🇦  🇹 🇦 🇼 🇮 🇱 🇮 🇸 ",
    "🇹 🇦 🇰 🇧 🇺 🇭  🇲 🇦 🇾 🇲 🇦 🇹 🇦 🇻 🇦 ",
    "Ø₩₴ⱧłɆ ₥Ø₭₳ ₭₳ ł₦ɆĐɆĐɄⱤØ",
    "₳₦Ʉ₱₳ ₴₳₴₳฿łⱧɆ₦ ₥Ø",
    "₩Ⱨ₳Ⱨ₳ ₥Ø₭₳ ₭₳ Ⱨł₱Ø₱Ø₮₳₥Ʉ₴",
    "ⱤɆ₱ɄⱤ₮₥Ʉ ₭Ʉ₦₲ ₭₳Ɏ₳ Ⱨ₩ɆⱧɆⱧɆⱧ",
    "ł₦ł₴ ₦₳ ฿₳฿₴₭łɆ ₦₳ Ɏ₳₦",
    "Ø₥₳ł ₮₳฿₳ ₭₳₴ł Ɇ?",
    "₩Ⱨ₳Ⱨ₳ ₲₳ⱠɆ₮ ₦₳",
    "₦₳₲ Đ₳฿Ʉ₲ Na😁😆",
    "₩₳₲ ₭₳ ₥₳ł₦Ɇ₴123",
    "łɎ₳₭ ₦₳ ₮Ø123",
    "₴ł₦Ø ฿₳₮ ₳₦₲ ₮₳V₳₥Ʉ123",
    "₭₳Ⱡ₥₳ ₥Ø ₮₳V₳₥Ø ฿₳฿₴₭łɆ",
    "Whahah Ansabe Pagud Kanah?!123😁😆",
    "LUko Hingengal Na siya"
];

// =============================================
// AUTO-REPLY IMAGE URLs
// Add direct image links here (must end in .jpg/.png/.gif etc.)
// The bot will randomly send one of these as a photo reply.
// Leave empty [] if you don't want image replies.
// =============================================

const imageReplies = [
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194629_438.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194540_649.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194604_631.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194615_502.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194225_980.webp",
];

module.exports = { replies, imageReplies };
