// =============================================
// AUTO-REPLY TEXT MESSAGES
// Replace each "" with your own message.
// The bot picks one at random each loop cycle.
// =============================================

const replies = [
    "ano",
    "why",
    "sino",
    "sml mo lang",
    "sml mo ngane",
    "di nga?",
    "cholesterol mo bab",
    "highblood mode to whahaha",
    "lt naasar",
    "luh inis yarn?",
    "wahahahaha pinag sasabe neto",
    "ta/baan mo pa",
    "sige ta/baan mo haha",
    "piggîé mode yan?",
    "hwaha lt monggi",
    "akala mo bot noh?",
    "akala ko rin e",
    "hwahahahah",
    "rage beyt si babskie oh",
    "nag dedeny ka ba?",
    "whahaha",
    "nag dabog na",
    "wag mo sirain pader niyong gawa sa kahoy",
    "wag mo sipaen lolamong tolog",
    "whaha",
    "trípko lolamo e",
    "pa sabi sa lolamo type ko siya",
    "reto moko sa lolamo nowna",
    "ayaw mo asawahin ko lolamo?",
    "nanaymo na lang ligawan ko haha",
    "nainis na",
    "hwahah amoy d.o ah",
    "mukha may mawawala ah",
    "tas erpat mo pala yung mawawala noh?",
    "aray mo pakak",
    "hahaha in¡inis ko lang ’to e bwahahaha",
    "jwu hwhaha",
    "jgh hwahaha",
    "na babanas to",
    "whahaa lt",
    "wag ka maines",
    "yare na galit na",
    "sml?",
    "whaha azar",
    "weh di nga",
    "yung ano?",
    "na ano si ano?",
    "sino nang ano kay ano",
    "bat siya inano ni ano haha",
    "tas ti/nera ko mamamo e",
    "syempre ala palag yan",
    "payag to na ako stepdad niya haha",
    "luh omeyak",
    "whaha lt",
    "whaha bat nalungkot to",
    "cheer up babskie",
    "◍˃ᵕ˂◍ ",
    "˃ 𖥦 ˂",
    "(•ૢ⚈͒⌄⚈͒•ૢ)",
    "ෆ(՞ ⌯'ᵕ'⌯ ՞)ෆ ̖́-",
    "azar whaha",
    "gagi di nga bot to haha",
    "naaning lt",
    "haha ano kaya oa",
    "sure ka kaya pa?",
    "baka pagod ka na",
    "gusto na neto mag sleep mode lt",
    "wag ka humilik",
    "hahahaha",
    "sabeng wag hihilek e",
    "lt tolog manteka yarn?",
    "wahhaha azar",
    "ano sa tingin mo bot ako?",
    "whahaha",
    " na aning ltness",
    "wala bot rito ahha",
    "pagod na to",
    "skl",
    "hahaha",
    "asar haha",
    "babskie na babskie talaga e btw way",
    "bangon naman",
    "ano puro higa",
    "grabe na ka tava yan insan",
    "bangon din pag may time @",
    "na azar na nga",
    "gusto na sumoko lt",
    "na papagod na haha lt",
    "walang time out rito",
    "sabayan mo lang amatsko",
    "hahaha nagalit lt",
    "wag ka mawala ah",
    "mamaya mawala ka e ",
    "pag ito nawala tatawagan ko to",
    "whahaa",
    "wag ka mag sleepwell",
    "lt ona na antok na?",
    "Skl ko lang haha",
    "azar na azar na to whaha",
    "na galit na naman",
];

// =============================================
// AUTO-REPLY IMAGE URLs
// Add direct image links here (must end in .jpg/.png/.gif etc.)
// The bot will randomly send one of these as a photo reply.
// Leave empty [] if you don't want image replies.
// =============================================

const imageReplies = [
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194629_438.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194540_649.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194604_631.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194615_502.webp",
    "https://file.garden/aahuG_hIDGRlXD24/IMG_20260326_194225_980.webp",
];

module.exports = { replies, imageReplies };
